### ISSUE TITLE
`UsersController#index`での`index.html.erb`の`undefined method` エラー

### ISSUE THREAD

**Issue by MIZOGUCHIKoki** [MIZOGUCHIKoki/MusicScoreManagementApp#38]
## 期限
2023/12/18
## 画面遷移
管理者としてログインした直後の画面です．
<img width="1582" alt="スクリーンショット 2023-12-18 15 22 00" src="https://github.com/MIZOGUCHIKoki/MusicScoreManagementApp/assets/94270819/ee2471fc-17bd-44e7-97e2-ebd0c3b78a33">

**Comment by MikamiShu** [comment]
SlackのDMで送った定義書通りに書けばエラーは解消されると思います．

**Comment by MIZOGUCHIKoki** [comment]
テスト

**Comment by MIZOGUCHIKoki** [comment]
テストコメント

**Comment by MIZOGUCHIKoki** [comment]
@OkuhiraShunri こちら，完了しましたか？

**Comment by OkuhiraShunri** [comment]
僕の画面からだと、管理者ログインをしてもパスワードとメールアドレスが違いますと表示されるだけで、そのエラー画面までいかないです

**Comment by MIZOGUCHIKoki** [comment]
PULL した後に，
```bash
$ bundle exec rails db:migrate:reset
$ bundle exec rails db:seed
```
でもだめですか？

管理者としては，`example@railstutorial.com` `password`，
非管理者としては，`example1@railstutorial.com` `password`です．

**Comment by OkuhiraShunri** [comment]
だめみたいです

**Comment by MikamiShu** [comment]
プライベートブラウザでアクセスしてもダメですか？

**Comment by OkuhiraShunri** [comment]
だめでした
