### ISSUE TITLE
`user_search`が`undefined method`と言われている

### ISSUE THREAD

**Issue by MIZOGUCHIKoki** [MIZOGUCHIKoki/MusicScoreManagementApp#39]
ログイン直後
## 画面遷移
<img width="1582" alt="スクリーンショット 2023-12-18 15 52 19" src="https://github.com/MIZOGUCHIKoki/MusicScoreManagementApp/assets/94270819/c75f973e-1e15-406a-99ae-3dc780e8612e">

**Comment by MikamiShu** [comment]
UsersController.indexにて，
@users = User.search_params()
と修正することで解決しました．
