### ISSUE TITLE
「管理者詳細」Viewエラー

### ISSUE THREAD

**Issue by MikamiShu** [MIZOGUCHIKoki/MusicScoreManagementApp#42]
サインイン>管理者の情報　ページにてエラーがあります．

＜一時的な対処法＞
views/users/show.html.erb の22，27行目を削除したところ問題なく表示されました．

＜原因？＞
1，コントローラとアクションの指定がうまくいっていない
2，指定はうまくいっており，指定先のアクションが働いていない
のどちらかかと．
<img width="1436" alt="スクリーンショット 2023-12-18 17 20 54" src="https://github.com/MIZOGUCHIKoki/MusicScoreManagementApp/assets/114971799/1a23c1d1-c5fd-4fc0-b78e-68725a0e2f20">

**Comment by 1250352** [comment]
解消
pathの指定を編集した結果うまくいきました

**Comment by 1250352** [comment]
pathの指定を編集したら解決しました．

**Comment by MIZOGUCHIKoki** [comment]
@MikamiShu こちら，解決しましたか？

**Comment by MIZOGUCHIKoki** [comment]
ありがとうございます．
@1250352 解決できていそうですか？できていそうなら @MikamiShu Closeお願いします．．

**Comment by 1250352** [comment]
解決できましたよ
viwe出ました

**Comment by MIZOGUCHIKoki** [comment]
ありがとう！
僕の方でCLoseしておきますね．
