### ISSUE TITLE
ユーザでのログイン時のエラー

### ISSUE THREAD

**Issue by MikamiShu** [MIZOGUCHIKoki/MusicScoreManagementApp#43]
ユーザでのサインイン直後のエラーです．

＜一時的な対処法＞
score_search_gakki_paramsにて，処理を
params.require(:score).permit(score: {})としたところうまくいきました．（全てのカラムを許可の意）

＜原因？＞
記述のミスかと．

＜関連＞
このエラーを修復直後，ユーザ詳細画面にてエラーが出ますが，対処法は「管理者詳細Viewエラー」でのものと同一です．
<img width="1436" alt="スクリーンショット 2023-12-18 17 43 01" src="https://github.com/MIZOGUCHIKoki/MusicScoreManagementApp/assets/114971799/3745b75c-96f6-4cbb-ab02-b28aaba3e55a">

**Comment by 1250385-Yamamoto** [comment]
現在、サインイン後のエラーについても調査中です

**Comment by 1250385-Yamamoto** [comment]
報告遅れました。観察は続けますが、一応は解決しているはずです。
