### ISSUE TITLE
ユーザとしてログインした直後

### ISSUE THREAD

**Issue by MikamiShu** [MIZOGUCHIKoki/MusicScoreManagementApp#44]
Issuesにある「ユーザとしてログインした直後のエラー」を一時的に取り除きユーザとしてログインした直後，`UsersController.home`ではなく`UsersController.show`が表示されています．

＜試したこと＞
- ルーティングを見る
- urlに関係していそうな`sessions_helper.store_location`を見る

をしましたがイマイチわかりませんでした．この辺が悪さをしていると思ったのですが...
全員アサインしておきます．

**Comment by MIZOGUCHIKoki** [comment]
見てみます．

**Comment by MikamiShu** [comment]
Homeに行こうとして不可能だった時にShowに行っている，ということですかね...

**Comment by MIZOGUCHIKoki** [comment]
エラー箇所除いたら，一応，HOMEに飛んでいるみたいだよ．
Uploading 画面収録 2023-12-19 18.25.23.mov…

**Comment by MikamiShu** [comment]
closeしていいですかね？

**Comment by MIZOGUCHIKoki** [comment]
おなしゃす．
