### ISSUE TITLE
ユーザを作成し，楽譜一覧に飛ぶとエラーが発生

### ISSUE THREAD

**Issue by 1250352** [MIZOGUCHIKoki/MusicScoreManagementApp#45]
users_controller.rbのhomeアクション
70行目，73行目
Scoreクラスを指定していないのが原因（Score.score_search）
73行目はscore_search_gakkiではないでしょうか？

<img width="785" alt="スクリーンショット 2023-12-18 213511" src="https://github.com/MIZOGUCHIKoki/MusicScoreManagementApp/assets/114973180/9f9395af-f49a-43fa-afc4-2d85daa70404">

**Comment by 1250385-Yamamoto** [comment]
score_search_gakkiとしても「メソッドが定義されていない」とのエラーが起きるため、調査してます。

**Comment by 1250385-Yamamoto** [comment]
View, model(scope), controllerともに現在も修正中です。もうしばらくお待ちください。

**Comment by 1250385-Yamamoto** [comment]
修正が完了しました。現段階ではなぜかチェックボックスが表示されていませんが。
