### ISSUE TITLE
管理者としてユーザ編集をした際のエラー

### ISSUE THREAD

**Issue by 1250352** [MIZOGUCHIKoki/MusicScoreManagementApp#47]
`users_controller.rb/update`
引数は`params[:id]`ではないでしょうか

<img width="801" alt="スクリーンショット 2023-12-19 135228" src="https://github.com/MIZOGUCHIKoki/MusicScoreManagementApp/assets/114973180/6369f166-2344-42d7-ac03-8351e77db2b1">

**Comment by tanakaryo341** [comment]
params[:id]の間違いです。今から修正し、動作確認します

**Comment by tanakaryo341** [comment]
編集ページが表示されるようになったので問題ないなったと思います。redirectされない、データベースに保存されていない問題は別で自分がissuesを立てます。後で確認お願いします

**Comment by 1250352** [comment]
確認できました
