### ISSUE TITLE
`correct_user_admin`か`current_user_admin`か

### ISSUE THREAD

**Issue by 1250352** [MIZOGUCHIKoki/MusicScoreManagementApp#48]
`users_controller.rb`の`corrent_user_admin`の名前
`correct_user_admin`，`current_user_admin`のどちらですか？
`currect_user_admin`だと思うんですがどうでしょう？

**Comment by 1250382KoukiYamada** [comment]
定義書ではcorrect_user_adminとなっています。

**Comment by 1250382KoukiYamada** [comment]
correctでもcurrentでもなくcurrectであるということですか？

**Comment by 1250352** [comment]
currect は間違いでした．
current ではないかということです
