### ISSUE TITLE
ログイン画面からアカウント作成画面に飛んだ際のエラー

### ISSUE THREAD

**Issue by 1250352** [MIZOGUCHIKoki/MusicScoreManagementApp#49]
`users/new.html.erb`
`form`メソッドが見つからないとなっているため，`form_with`で囲む必要があると思います．
```erb
<%= form_with model: @user do |f| %>
  <%= f.label :name, '名前' %>
  <%= f.text_field :name %>
  <%= f.submit "送信" %>
<% end %>
```
このような感じ

<img width="785" alt="スクリーンショット 2023-12-19 144051" src="https://github.com/MIZOGUCHIKoki/MusicScoreManagementApp/assets/114973180/72cd9617-1aa3-4447-9d28-282288660a8e">

**Comment by 1250385-Yamamoto** [comment]
formに関しては修正しました
