### ISSUE TITLE
管理者として、userの情報更新(update)ができない

### ISSUE THREAD

**Issue by tanakaryo341** [MIZOGUCHIKoki/MusicScoreManagementApp#51]
管理者としてログイン、あるユーザ選択後、編集にて編集内容を打ち込み更新ボタンを押しても画面遷移をしていません。
画面遷移をしていないというよりはデータが更新されていないように感じる。
ただ、`update`が`false`の際を`action: :index`に変更しても画面遷移しないため根本的に`redirect_to`，`render`の使い方を再確認する必要がある。

現状では、redirectなどの問題であるため、assignは @tanakaryo341 のみにする。

**Comment by MIZOGUCHIKoki** [comment]
「管理者として」だけですか？一般ユーザの自分の情報を更新するのはどうでしょう？

**Comment by tanakaryo341** [comment]
できませんでした

**Comment by MikamiShu** [comment]
`return unless correct_user_admin`
この一文が悪さをしています．コメントアウトをしたところ，一般ユーザの自分の情報更新は問題なく行えることを確認しました．

**Comment by MikamiShu** [comment]
追記：
管理者側からユーザの情報も問題なく変更できました．

**Comment by tanakaryo341** [comment]
確認できました。ありがとうございます
