### ISSUE TITLE
Scoreを登録するボタンを押下してもどこにもリダイレクトしない

### ISSUE THREAD

**Issue by MIZOGUCHIKoki** [MIZOGUCHIKoki/MusicScoreManagementApp#52]
画面録画の通り．

https://github.com/MIZOGUCHIKoki/MusicScoreManagementApp/assets/94270819/c8b3e76e-493e-4b79-bf59-5d313182f082

関連事象
として #51 をあげる．

**Comment by tanakaryo341** [comment]
動画おくれてないかと

**Comment by tanakaryo341** [comment]
あと、同様の問題と思われるのが #51 でも起きてます

**Comment by MIZOGUCHIKoki** [comment]
`app/models/score.rb`のバリデートがまずいことが判明．

```Ruby
validates :name, presence: true, length: { maximum: 50 }
```
の`presence: true`を除くと問題ない．

**Comment by MIZOGUCHIKoki** [comment]
@MikamiShu Issuesクローズお願いします．
