### ISSUE TITLE
楽曲登録画面の配置

### ISSUE THREAD

**Issue by MikamiShu** [MIZOGUCHIKoki/MusicScoreManagementApp#53]
ユーザでサインイン>楽譜一覧>楽譜を登録する　ページにて，
使用楽器がチェックボックスになっておらず，また隠されていません．Notionを見て修正してください．

**Comment by 1250385-Yamamoto** [comment]
楽譜を登録する際には入力フォームに使用する楽器の0~10の数を入れるものだと考えていました。またチェックボックスを用いるのは、検索をかけるときだけという認識なのですが、違いましたでしょうか？
https://kut-sw-engineering.slack.com/archives/C06858HPLLR/p1702909348479709?thread_ts=1702909348.479709&cid=C06858HPLLR
