### ISSUE TITLE
管理者情報編集エラー

### ISSUE THREAD

**Issue by MikamiShu** [MIZOGUCHIKoki/MusicScoreManagementApp#55]
管理者としてログイン>管理者の情報>編集　と遷移後の画面にて，
バリデーションに沿っていないパスワードを入力するとエラーが発生します．

＜原因？＞
綴ミスでしょう．

<img width="1436" alt="スクリーンショット 2023-12-20 16 28 14" src="https://github.com/MIZOGUCHIKoki/MusicScoreManagementApp/assets/114971799/9b152d11-892e-476f-9895-56b82b5d962d">

**Comment by MikamiShu** [comment]
また，先日チラッとお伝えした通り，リダイレクトだとflashが表示されない可能性があります．
挙動を見てみないとわかりませんが，表示されなければrenderとしてください．

**Comment by tanakaryo341** [comment]
綴りミス、render.nowに修正することで設計書通りの動作を確認しました
