### ISSUE TITLE
ユーザ削除時のエラー（`ApplicationController.signed_in_user`）

### ISSUE THREAD

**Issue by MikamiShu** [MIZOGUCHIKoki/MusicScoreManagementApp#56]
ユーザとしてログイン>マイページ>ユーザ削除　と遷移した時に起こるエラー．

＜原因？＞
リダイレクトがうまくいっていない．おそらくは記述方法が違うかと．

<img width="1436" alt="スクリーンショット 2023-12-20 17 50 59" src="https://github.com/MIZOGUCHIKoki/MusicScoreManagementApp/assets/114971799/5784326d-d233-4784-babf-efe28aaf3201">

**Comment by MIZOGUCHIKoki** [comment]
@1250382KoukiYamada レビュお願いします．

**Comment by 1250382KoukiYamada** [comment]
確認しました。
