### ISSUE TITLE
楽譜詳細画面にて演奏時間，パート数が出力されない

### ISSUE THREAD

**Issue by MikamiShu** [MIZOGUCHIKoki/MusicScoreManagementApp#57]
ユーザとしてログイン>楽譜詳細　と遷移した先のエラー

＜原因？＞
int型だけが出力されていないため，記述方法が原因か．

**Comment by 1250352** [comment]
パート数を表示させるように修正した
timeについては検討中

**Comment by MIZOGUCHIKoki** [comment]
Schemaを`m_time`へ変更してみようかな．

**Comment by MIZOGUCHIKoki** [comment]
- `UsersController#home` VIEWの timeスキーマの変更 @OkuhiraShunri 
- `UserController#show` VIEWの itmeスキーマの変更 @1250352

**Comment by 1250352** [comment]
score_paramsにm_timeを追加したことで改善した
