### ISSUE TITLE
楽譜編集画面エラー

### ISSUE THREAD

**Issue by MikamiShu** [MIZOGUCHIKoki/MusicScoreManagementApp#58]
ユーザとしてログイン>楽譜編集　と遷移した先で起こるエラー．

＜原因？＞
form_with を記述していないためかと．

<img width="1436" alt="スクリーンショット 2023-12-21 14 46 04" src="https://github.com/MIZOGUCHIKoki/MusicScoreManagementApp/assets/114971799/33e1d8c1-4660-4a04-a334-03dd4b1a7fd8">

**Comment by MIZOGUCHIKoki** [comment]
名前が変更できない問題

**Comment by MIZOGUCHIKoki** [comment]
@tanakaryo341 レビュお願いします．

**Comment by tanakaryo341** [comment]
編集を選択時に、編集画面が出るようになりました。
ただ、変更情報を失敗した際のflashが出ていないです。こちらは自分が担当ですので修正後、確認してこのissueを閉じます

**Comment by tanakaryo341** [comment]
flashが反映されるの確認しました
