### ISSUE TITLE
homeでのソートや楽器以外の検索するためのviewのボタンが存在しない

### ISSUE THREAD

**Issue by tanakaryo341** [MIZOGUCHIKoki/MusicScoreManagementApp#61]
## 要件
`home`の`view`に編曲者、作曲者、グレードのソートを行うボタンを作成してください。
## 期限
2023/12/22（金）まで

**Comment by MIZOGUCHIKoki** [comment]
プルダウン
- ソートなし
- 昇順
- 降順

**Comment by OkuhiraShunri** [comment]
![キャプチャ](https://github.com/MIZOGUCHIKoki/MusicScoreManagementApp/assets/114981884/ca3f7b3b-2918-45a6-bd2f-4dcac0d5e5fa)
![キャプチャ2](https://github.com/MIZOGUCHIKoki/MusicScoreManagementApp/assets/114981884/d05df36c-36f0-44c9-96d5-2414b28e7dbd)
ソートのプルダウンを作ってるのですが、写真のコードでは上手くいかないのですが、原因わかる方いませんか

**Comment by OkuhiraShunri** [comment]
https://github.com/MIZOGUCHIKoki/MusicScoreManagementApp/assets/114981884/03236c02-5eda-4f1d-ae79-e8153ff8e71a

**Comment by MIZOGUCHIKoki** [comment]
ルーティングがうまく行っていないようですね、、、
`params[:id]`

**Comment by OkuhiraShunri** [comment]
この場合どのようにルーティングされるべきでしょうか？

**Comment by OkuhiraShunri** [comment]
プルダウンの入力を受け取るためにparams[:order]という書き方をしていますが、これであっているのかもいまいちよくわからないです。:orderという変数？がモデルなど他のファイルで定義されていなくても、homeアクションとviewファイルで:orderを書いていれば、homeアクション内でプルダウンの入力値として受け取れるのでしょうか？

**Comment by MIZOGUCHIKoki** [comment]
<img width="280" alt="image" src="https://github.com/MIZOGUCHIKoki/MusicScoreManagementApp/assets/94270819/a30902d9-0001-4818-98c7-7f080d77a254">

`home/13` にPOSTはできませんね．

**Comment by MIZOGUCHIKoki** [comment]
@tanakaryo341 Closeお願いします！
