### ISSUE TITLE
リリースノート，お問い合わせページを作成する

### ISSUE THREAD

**Issue by MIZOGUCHIKoki** [MIZOGUCHIKoki/MusicScoreManagementApp#63]
`static_pages`コントローラを作成し，各アクションに対応するVIEWを記述する．

**Comment by MIZOGUCHIKoki** [comment]
コントローラ，VIEWの定義は終わりました．Routingも済みました．
Footerへリンクの追加もしました．

**Comment by MIZOGUCHIKoki** [comment]
@1250382KoukiYamada に引き継ぎました．

**Comment by 1250382KoukiYamada** [comment]
お問い合わせページのメールアドレスって決まってますか？

**Comment by MIZOGUCHIKoki** [comment]
とりあえず，example@example.com  でお願いします！

**Comment by 1250382KoukiYamada** [comment]
作成しました

**Comment by MIZOGUCHIKoki** [comment]
ありがとう．LGTMです．
