### ISSUE TITLE
各楽器の登録が0,1のみしかできない

### ISSUE THREAD

**Issue by tanakaryo341** [MIZOGUCHIKoki/MusicScoreManagementApp#64]
validatesにより、各楽器数が0,1しか登録することができないが、設計書では10まで登録可能であるため、
修正が必要である。

**Comment by MIZOGUCHIKoki** [comment]
@tanakaryo341 今日中にお願いします．

**Comment by tanakaryo341** [comment]
修正しましたので確認お願いします

**Comment by MikamiShu** [comment]
0〜10まで登録できることは確認しましたが，
「あいうえお」等でも登録することができ，この場合0になります．

**Comment by tanakaryo341** [comment]
文字のみの入力、数値(intのみ)、０から5までのみ入力できることを確認しました

**Comment by MikamiShu** [comment]
「0から5までのみ」とありますが，10まで登録できるようですが．グレードの話でしょうか？
整数しか受け付けないことは確認しました．

**Comment by tanakaryo341** [comment]
少しグレードを触ったので混同していました。楽器なので10までですね修正します

**Comment by MikamiShu** [comment]
グレードは5までで合ってますよ．
私が話しているのは登録楽器の話です．

**Comment by tanakaryo341** [comment]
文のこととコードやらがごちゃ混ぜになってました。
修正箇所ないです。お騒がせしました
