### ISSUE TITLE
ユーザ編集ページへリダイレクトしない

### ISSUE THREAD

**Issue by MikamiShu** [MIZOGUCHIKoki/MusicScoreManagementApp#65]
ユーザとしてログイン>ユーザ詳細>編集　と遷移した際，編集ページへリダイレクトしない．

**Comment by 1250352** [comment]
こっちの方では編集にリダイレクトするんですが…

**Comment by 1250352** [comment]
編集へのリダイレクト下のようになっていますか？

<img width="679" alt="スクリーンショット 2023-12-22 120445" src="https://github.com/MIZOGUCHIKoki/MusicScoreManagementApp/assets/114973180/2c7b5670-ef9d-4826-be31-79b4ad864314">

**Comment by MikamiShu** [comment]
PULLしていただけたらわかるかと思いますが，link_toからbutton_toに変更しています．
link_toに戻してもリダイレクトしませんでした．

**Comment by MikamiShu** [comment]
嘘ですlink_toに戻したら動作しました，こちらで修正します

**Comment by MikamiShu** [comment]
解決しました．
