### ISSUE TITLE
管理者としてユーザを削除した場合のリダイレクト先

### ISSUE THREAD

**Issue by MikamiShu** [MIZOGUCHIKoki/MusicScoreManagementApp#66]
管理者としてログイン>個別ユーザ>アカウント削除　と遷移した先．
削除は問題なく行われているが，リダイレクト先がindexとなっていない．

＜原因？＞
UsersController.destroyが原因かと．

**Comment by 1250385-Yamamoto** [comment]
遷移先を index としました

**Comment by MikamiShu** [comment]
変わっていないようですが．

**Comment by 1250385-Yamamoto** [comment]
ただいまpushしました。しかしrails testでエラーが発生しているため、後ほど解消します。

**Comment by MIZOGUCHIKoki** [comment]
@1250385-Yamamoto テストエラー，こっちで修正しますね．

**Comment by MIZOGUCHIKoki** [comment]
@MikamiShu 確認してOKだったらCloseお願いします．

**Comment by MikamiShu** [comment]
確認しました．
