### ISSUE TITLE
楽譜登録時の挙動

### ISSUE THREAD

**Issue by MikamiShu** [MIZOGUCHIKoki/MusicScoreManagementApp#67]
ユーザとしてログイン>楽譜登録 と遷移した後の話．

楽譜登録の際，「演奏時間」にテキストを入れても受理され，登録後は「0分00秒」として表示される．

＜対処＞
int型しか通らなくすること．

**Comment by tanakaryo341** [comment]
修正しましたので確認お願いします

**Comment by MikamiShu** [comment]
確認しました．
