### ISSUE TITLE
管理者として楽譜を削除した際の挙動

### ISSUE THREAD

**Issue by MikamiShu** [MIZOGUCHIKoki/MusicScoreManagementApp#68]
管理者としてログイン>ユーザ選択>楽譜一覧へ>削除　と遷移した先での挙動．

管理者としてログインしているのに，楽譜を削除すると`UsersController.home`へ遷移します．
＜原因？＞
Scores Controller.destroy が原因かと．

**Comment by 1250385-Yamamoto** [comment]
遷移先を users_controller.index としました

**Comment by MikamiShu** [comment]
変わらずUsersContorller.homeに遷移しているようですが．

**Comment by MikamiShu** [comment]
変わっていないようです．

**Comment by 1250385-Yamamoto** [comment]
rails testの件でpushが遅れていました。現在は修正されています。確認が二度手間となってしまい、すみません。

**Comment by MIZOGUCHIKoki** [comment]
@MikamiShu 確認してOKだったらCloseお願いします！

**Comment by MikamiShu** [comment]
確認しました．
