### ISSUE TITLE
使用楽器検索の実装について

### ISSUE THREAD

**Issue by 1250385-Yamamoto** [MIZOGUCHIKoki/MusicScoreManagementApp#69]
思うように使用楽器検索を実装できないので不審な点があればご指摘いただきたいです。
スコープ内のwhereにて条件を「1以上」(piccolo: 1.. あるいは "piccolo >= 1")とすると条件にあった楽譜を表示することができるのですが、即値以外の、例えばsearch_params[:piccolo]とするとうまく機能しません。
チェックボックスの値をパラメータとして入手していることは確認しており、また引数に関して条件式内で以上、イコールで表示する一覧が異なることから、受け渡し自体は上手くいっているかと思います。引き続き調査しますが、時間がかかりすぎたため、共有いたします。

行っている操作はほかの検索と同様で、入力値を引数としたスコープがうまく機能していないのが現状です。

**Comment by MIZOGUCHIKoki** [comment]
デバッグで
```Ruby
puts "piccolo value: #{search_params[:piccolo]}"
```
してみたらどうでしょうか？

**Comment by 1250385-Yamamoto** [comment]
解決しました。
