### ISSUE TITLE
複数の楽譜を登録し，ソートした際の挙動

### ISSUE THREAD

**Issue by MikamiShu** [MIZOGUCHIKoki/MusicScoreManagementApp#73]
ユーザとしてログインした後の挙動．

複数の楽譜が登録された状態で検索により候補を絞り，その後にソートをかけると全ての楽譜が表示されますが，これは意図した挙動ですか．

**Comment by tanakaryo341** [comment]
ソートと検索は同時に使用しないというふうに内部設計書、話し合いで決まっていたと記憶していたので、現状では仕様です。

おそらく検索状態からのソートも可能ではあると思います。

**Comment by MikamiShu** [comment]
いろいろラベル部も貼られてなにかにいれられてもいるのでcloseは保留しておきます

**Comment by MIZOGUCHIKoki** [comment]
本当は，検索した中からソートもしたいよね、、、
です． @tanakaryo341

**Comment by MIZOGUCHIKoki** [comment]
まじありがとうです．LGTMです．
