### ISSUE TITLE
valueの値がnilのときにviewエラー

### ISSUE THREAD

**Issue by 1250385-Yamamoto** [MIZOGUCHIKoki/MusicScoreManagementApp#74]
ユーザとしてログイン後、楽譜一覧画面にて楽曲名検索フォームに無記入で検索を行うと以下のエラーが発生します。
再読み込み後も記入された文字列を記憶しておくものだと思いますが、何もないことで、nilとなってしまうのだと思います。対象箇所を削除することで解消するかと。
![スクリーンショット 2023-12-26 162026](https://github.com/MIZOGUCHIKoki/MusicScoreManagementApp/assets/114971895/1feda6ea-fc50-4523-a5cc-4512e5972e67)

**Comment by 1250352** [comment]
修正箇所が思い当たらないのですが，
下の画像のように75行目をコメントアウトしたらhomeが表示されるんですけどどうですかね？

<img width="677" alt="スクリーンショット 2023-12-26 172503" src="https://github.com/MIZOGUCHIKoki/MusicScoreManagementApp/assets/114973180/cead9e67-e75f-4ef8-aebf-ac034884766f">

**Comment by MikamiShu** [comment]
私がPUSHした時はなかったんですが...
そこが空でも大丈夫なようにfetchを使って入力を取得しているつもりですし...

**Comment by MikamiShu** [comment]
直近のPUSHに問題がありそうですね

**Comment by 1250385-Yamamoto** [comment]
もう少し調べてみます。

**Comment by 1250385-Yamamoto** [comment]
修正完了しました。原因は score_search_gakki_params の定義が間違っていたことでした。
ご協力ありがとうございました。
