### ISSUE TITLE
一つのアカウントに対して複数ユーザが同時にアクセスできない問題

### ISSUE THREAD

**Issue by 1250385-Yamamoto** [MIZOGUCHIKoki/MusicScoreManagementApp#86]
現状では、同一のアカウントに複数ユーザがログインしようとすると、先にログインしていたユーザは再ログインを求められてしまいます。これは運用において致命的な問題であり、その解決法がまだ見つかっていないため、皆様から案を募りたいです。

**Comment by MIZOGUCHIKoki** [comment]
色々考えてるんですけどねぇ・・・だいぶ致命的

**Comment by 1250385-Yamamoto** [comment]
画期的な解決策が提案されたため、この問題をクローズします。
